### ISSUE TITLE
AWS loop example uses watch frequency of 30d

### ISSUE THREAD

**Issue by edmorley** [dmathieu/dice#15]
The example here uses `-w=30d`:
https://github.com/dmathieu/dice/blob/5bb565bf03465a26ff667dd139c997604f745d0d/examples/loop-aws.yml#L56

...which means a watch frequency of 30 days (as opposed to the default of 5 minutes).

I'm presuming this was meant to be `-u=30d` (ie max uptime of 30d, increased from the default of 10d)?

**Comment by dmathieu** [comment]
Thank you Ed 😸 
I've removed the argument entirely. The default of 10d is sensible, and makes the example easier to read. 9e93d869147c3211d6def0ca04966ea149dca53e

**Comment by edmorley** [comment]
Thank you :-)
